version: "3.5"
services:
    web_db:
        image: "postgres:14.5-alpine"
        container_name: "actix_web"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - actix_web_dbdata:/var/lib/postgresql/data
        # networks:
        #     - postgres

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:6.12
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/var/lib/pgadmin
        restart: unless-stopped
        ports:
            - "${PGADMIN_PORT:-5050}:80"

volumes:
    actix_web_dbdata:
    pgadmin:
